# Mobile App Configuration
type=APP

# Mobile Browser Configuration
browserName=Chrome

# Device Details
deviceName=KFR8AYHQE67DFYMJ
platformName=Android
platformVersion=15

# Application Details
appPackage=com.omr_branch
appActivity=com.omr_branch.MainActivity

# Automation Engine
automationName=UIAutomator2

# Environment URL
url=https://www.omrbranch.com/